# Complete KPF Test Application Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpf-test-app
  
  labels:
    app: kpf-test-app
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpf-test-app
  template:
    metadata:
      labels:
        app: kpf-test-app
        version: v1.0.0
    spec:
      containers:
      - name: kpf-test-app
        image: python:3.12-slim
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        command: ["python3", "/app/restart-test-app.py"]
        volumeMounts:
        - name: app-code
          mountPath: /app
          readOnly: true
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-code
        configMap:
          name: kpf-test-app-config
          defaultMode: 0555  # Read and execute permissions
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: kpf-test-app-service
  
  labels:
    app: kpf-test-app
    version: v1.0.0
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 8080
    protocol: TCP  
    name: metrics
  selector:
    app: kpf-test-app